name: Deploy to AWS

on:
  push:
    branches:
      - main  # `main` ブランチに push したらデプロイ実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ 1. リポジトリのコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ 2. AWS にログイン（GitHub Secrets を使用）
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1  # ← 修正（ECR のリージョンに合わせる）

      # ✅ 3. Docker をセットアップ
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # ✅ 4. AWS ECR にログイン
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_URL }}

      # ✅ 5. Docker イメージをビルド＆プッシュ
      - name: Build and push Docker image
        run: |
          IMAGE_TAG=$(date +%s)
          docker build -t ${{ secrets.AWS_ECR_URL }}/webapp:$IMAGE_TAG ./app
          docker push ${{ secrets.AWS_ECR_URL }}/webapp:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # ✅ 6. AWS ECS のタスク定義を更新してデプロイ
      - name: Deploy to Amazon ECS
        run: |
          aws ecs update-service --cluster my-cluster --service my-service --force-new-deployment
